version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nuvia
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./Backend
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nuvia
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    command: ["npm", "run", "start:wait"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
